// <auto-generated />
namespace WebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Teste0706 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Teste0706));
        
        string IMigrationMetadata.Id
        {
            get { return "201906072056155_Teste0706"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
